config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :groups
  resources :users, only: [:index, :edit, :update, :destroy] do
    post :reset_password
    post :reset_confirmation
    resources :events, only: [:index]
  end
  resources :events, only: [:index]
  use_doorkeeper_openid_connect
  use_doorkeeper

  root to: "application#home"
end

app/models/group.rb
class Group < ApplicationRecord
  validates_presence_of :name
  has_and_belongs_to_many :users

  def roles_as_array
    roles.split(/[\s\n,;]/).select(&:present?)
  end

  def resources_as_array
    resources.split(/[\s\n,;]/).select(&:present?)
  end

  def ip_restriction= value
    if value.is_a? String
      super(value.split(/[,|\s]/).select(&:present?))
    else
      super(value)
    end
  end

  def ip_restriction
    read_attribute(:ip_restriction).present? ? read_attribute(:ip_restriction) : []
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @users = @group.users.order(:email).to_a
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :roles, :resources, :ip_restriction)
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :roles %>
    <%= form.text_area :roles %>
  </div>

  <div class="field">
    <%= form.label :ip_restriction %>
    <%= form.text_field :ip_restriction %>
  </div>

  <div class="field">
    <%= form.label :resources %>
    <%= form.text_area :resources %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Destroy', @group, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.name, group %></li>
  <% end %>
</ul>
<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1>Group:<br/><%= @group.name %></h1>
<h2>Roles</h2>
<ul>
  <% @group.roles_as_array.each do |role| %>
  <li><%=role%></li>
  <% end %>
</ul>

<h2>Resources</h2>
<ul>
  <% @group.resources_as_array.each do |role| %>
  <li><%=role%></li>
  <% end %>
</ul>

<h2>Users</h2>
<ul>
<% @users.each do |user| %>
<li><%=link_to user.email, edit_user_path(user) %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>