config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :groups
  resources :users, only: [:index, :edit, :update, :destroy] do
    post :reset_password
    post :reset_confirmation
    resources :events, only: [:index]
  end
  resources :events, only: [:index]
  use_doorkeeper_openid_connect
  use_doorkeeper

  root to: "application#home"
end

app/models/user.rb
class User < ApplicationRecord
  devise :two_factor_authenticatable, otp_secret_encryption_key: Rails.application.credentials.otp_secret_encryption_key
  devise :registerable, :timeoutable, :recoverable, :rememberable, :validatable, :trackable, :confirmable, :lockable

  after_create :track_create_event
  before_update :track_events
  attr_accessor :performed_by_user

  has_many :access_grants,
    class_name: "Doorkeeper::AccessGrant",
    foreign_key: :resource_owner_id,
    dependent: :destroy

  has_many :access_tokens,
    class_name: "Doorkeeper::AccessToken",
    foreign_key: :resource_owner_id,
    dependent: :destroy

  has_many :events

  has_and_belongs_to_many :groups

  before_save :set_uuid

  alias_method :email_verified?, :confirmed? # open_id semantics

  def some_kind_of_admin?
    admin? || user_admin?
  end

  def roles_as_array
    groups.flat_map { |g| g.roles_as_array }
  end

  def resources_as_array
    groups.flat_map { |g| g.resources_as_array }
  end

  def to_param
    uuid
  end

  def adheres_to_ip_restriction?(ip)
    ip_restriction.empty? || ip_restriction.include?(ip)
  end

  def ip_restriction= value
    if value.is_a? String
      super(value.split(/[,|\s]/).select(&:present?))
    else
      super
    end
  end

  def ip_restriction
    read_attribute(:ip_restriction).present? ? read_attribute(:ip_restriction) : groups.flat_map { |g| g.ip_restriction }.compact
  end

  private

  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def track_create_event
    events.create(name: :create, ip_address: current_sign_in_ip)
  end

  def track_event_attributes(name:)
    {name: name, ip_address: performed_by_user&.current_sign_in_ip || current_sign_in_ip, performed_by_user: performed_by_user}
  end

  def track_events
    if changes["email"]
      events.create(track_event_attributes(name: :email_change))
    elsif changes["unconfirmed_email"]&.[](1)
      events.create(track_event_attributes(name: :email_change_request))
      if changes["confirmation_sent_at"]
        events.create(track_event_attributes(name: :sent_confirmation_instructions))
      end
    elsif changes["current_sign_in_at"]
      events.create(track_event_attributes(name: :sign_in))
      if changes["confirmation_sent_at"]
        events.create(track_event_attributes(name: :sent_confirmation_instructions))
      end
    elsif changes["encrypted_password"]
      events.create(track_event_attributes(name: :password_update))
    elsif changes["reset_password_sent_at"]
      events.create(track_event_attributes(name: :sent_reset_password_instructions))
    elsif changes["confirmation_sent_at"]
      events.create(track_event_attributes(name: :sent_confirmation_instructions))
    elsif changes["name"]
      events.create(track_event_attributes(name: :name_change))
    elsif changes["ip_restriction"]
      events.create(track_event_attributes(name: :ip_restriction_updated))
    elsif changes["confirmed_at"]
      events.create(track_event_attributes(name: :email_confirmed))
    elsif changes.empty?
      # noop
    elsif Rails.env.test? || Rails.env.development?
      raise "Unknown change: #{changes.inspect}"
    else
      events.create(track_event_attributes(name: :update))
    end
  end
end

# After each sign in, verify if the user is allowed to sign in from the current IP address
Warden::Manager.after_set_user except: :fetch do |record, warden, options|
  if record.respond_to?(:adheres_to_ip_restriction?) && warden.authenticated?(options[:scope])
    unless record.adheres_to_ip_restriction?(warden.request.remote_ip)
      scope = options[:scope]
      warden.logout(scope)
      throw :warden, scope: scope, message: "Not allowed"
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  invisible_captcha only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user_admin!
  before_action :set_user, only: [:update, :edit, :destroy, :reset_password, :reset_confirmation]

  def index
    @users = User.order(:email).all
  end

  def edit
  end

  def update
    if @user.update(user_params.merge(performed_by_user: current_user))
      redirect_to users_path, notice: "#{@user.email} has been succesfully updated"
    else
      render :edit
    end
  end

  def reset_password
    @token = @user.send_reset_password_instructions
    @resource = @user
  end

  def reset_confirmation
    @user.send_confirmation_instructions
    @token = @user.confirmation_token
    @resource = @user
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: "#{@user.email} has been succesfully removed"
    else
      redirect_to user_path(@user), notice: "Removing failed"
    end
  end

  private

  def set_user
    @user = User.find_by_uuid(params[:user_id] || params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :user_admin, :ip_restriction, group_ids: [])
  end
end

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= form_with(model: @user) do |form| %>
<%= simple_format @user.errors.full_messages.join("\n\n")%>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :ip_restriction %>
    <%= form.text_field :ip_restriction %>
  </div>

  <div class="field">
    <%= form.check_box :user_admin %><%= form.label :user_admin %>
  </div>
  <div class="field">
    <%= form.label :groups %>
    <%= form.collection_check_boxes :group_ids, Group.all, :id, :name%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<h2>Alternative actions</h2>
<%= button_to "Reset password", user_reset_password_url(@user) %>
<%= button_to "New confirmation", user_reset_confirmation_url(@user) %>
<%= button_to "Delete user", user_url(@user), method: :delete%>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:name)%></th>
      <th><%= User.human_attribute_name(:email)%></th>
      <th><%= User.human_attribute_name(:current_sign_in_at)%></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, edit_user_path(user) %></td>
    <td><%= link_to user.email, edit_user_path(user) %></td>
    <td><%= link_to(I18n.l(user.current_sign_in_at), user_events_path(user)) if user.current_sign_in_at%></td></tr>
  <% end %>
  </tbody>
</table>

app/views/users/reset_confirmation.html.erb
<h1>New confirmation</h1>
<p>The following mail has been sent to the user, you may copy the text / url.</p>
<div class="print-preview">
<%= render partial: 'devise/mailer/confirmation_instructions'%>
</div>

app/views/users/reset_password.html.erb
<h1>New confirmation</h1>
<p>The following mail has been sent to the user, you may copy the text / url.</p>
<div class="print-preview">
<%= render partial: 'devise/mailer/reset_password_instructions'%>
</div>