config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :groups
  resources :users, only: [:index, :edit, :update, :destroy] do
    post :reset_password
    post :reset_confirmation
    resources :events, only: [:index]
  end
  resources :events, only: [:index]
  use_doorkeeper_openid_connect
  use_doorkeeper

  root to: "application#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CentralLogin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <% if current_user&.some_kind_of_admin? %>
    <nav>
      <ul>
        <%= menu_link_to 'CentralLogin', root_path, {wrap: true, only_exact_path_match: true} %>
        <%= menu_link_to 'Users', users_path, {wrap: true} %>
        <%= menu_link_to 'Groups', groups_path, {wrap: true} if current_user.admin? %>
        <%= menu_link_to 'Events', events_path, {wrap: true} if current_user.admin? %>
        <% if current_user&.admin? %>
          <li><%= link_to 'Manage Applications', oauth_applications_path %></li>
          <% end %>
      </ul>
      <ul>
      <% if current_user %>
        <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'New user session path', new_user_session_path%></li>
      <% end %>
      </ul>
    </nav>
    <% end %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>